### ISSUE TITLE
Multi WebPart testing

### ISSUE THREAD

**Issue by andrewgascoigne** [sebastienlevert/spfx-angular-boilerplate#10]
[spfx-angular-boilerplate.zip](https://github.com/sebastienlevert/spfx-angular-boilerplate/files/1262843/spfx-angular-boilerplate.zip)

Hi Sebastien, 

Apologies for not replying sooner, I have been away. I have attached the code minus the node modules folder. In addition since my original post I have implemented the Angular Materials controls and started to implement cascading drop downs as per this article:

https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/use-cascading-dropdowns-in-web-part-properties

Again - modifying the cascading drop downs has some "interesting" challenges. 

Feel free to implement any of the tweaks I have looked at in any of your source. I appreciate your efforts!!

Let me know if you need anything else. I will continue to have a look at this from my side so will let you know if I find anything. 

Thanks 

Andrew

**Comment by sebastienlevert** [comment]
Latest version of the Master merge fixes this issue! Please have a look and update your base code to use the latest version of the boilerplate! Thanks! Closing the issue now!
