### ISSUE TITLE
Angular 2 on SharePoint Hosted Server

### ISSUE THREAD

**Issue by sonalien** [sebastienlevert/spfx-angular-boilerplate#12]
How can we deploy Web Part of Angular 2 on SharePoint Hosted Server without using Node?
If we stop the Node JS server, the application also stops on SharePoint.

**Comment by sebastienlevert** [comment]
For now, this solution only applies to SharePoint Framework Online (never tested On-Premises). But for your scenario, please host the files somewhere else as this is the best practice approach. Please read about it here : https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-2016-support. I will close this issue, feel free to reopen it if it doesn't work for you!
